title: "Dev Learning Terminal"
description: "My blog tracking my first Git clone to full-stack hacker"
author: "Jack Usherr"

style: dark
listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag
